Add support for Slashing Parameters and Missed Blocks per Signing Window
kilnfi/cosmos-validator-watcher pull request #85
Opened 2024-11-06 13:39 UTC by qwertzlbert

This pull request introduces a new set of features for exporting network slashing parameters to Prometheus, along with additional metrics to monitor validator performance and slashing conditions.

**Key Changes**
Prometheus Metrics for Slashing Parameters:

Exports key network slashing parameters, such as the Signing Window size and Slashing Penalties to Prometheus.
Validator “Missed Blocks per Signing Window” Tracking:

Adds the ability to query the current count of "Missed Blocks per Signing Window" for each validator. This metric aligns with the network’s threshold for determining whether a validator should be jailed.
Optional Slashing Metrics Collection:

Users can disable the collection of slashing-related metrics by using the --no-slashing argument.
Consensus Address Matching for Validator Metrics:

The validator's public key (PubKey) and the network's detected human-readable prefix are used to derive the consensus address. This enables proper mapping of metrics returned from the SigningInfo module, which provides metrics in the Bech32 Consensus Address format.

**Testing and Validation**
This change has been tested across several networks, ensuring compatibility and accurate metric collection:

Networks Tested:
- Axelar
- Cosmos
- Band
-Osmosis
- Injective
- Zeta
- Agoric

Additionally a unit tests have been added and updated.

**Additional Notes**
These additions will enhance monitoring and alerting capabilities for validator operators by providing real-time insights into slashing parameters and validator performance. This feature set will improve operational awareness, helping operators avoid slashing events.
---
New prometheus metrics added:
```
.
.
.
# HELP cosmos_validator_watcher_signed_blocks_window Number of blocks per signing window
# TYPE cosmos_validator_watcher_signed_blocks_window gauge
cosmos_validator_watcher_signed_blocks_window{chain_id="cosmoshub-4"} 10000
# HELP cosmos_validator_watcher_min_signed_blocks_per_window Minimum number of blocks required to be signed per signing window
# TYPE cosmos_validator_watcher_min_signed_blocks_per_window gauge
cosmos_validator_watcher_min_signed_blocks_per_window{chain_id="cosmoshub-4"} 0.05
# HELP cosmos_validator_watcher_min_signed_blocks_per_window Minimum number of blocks required to be signed per signing window
# HELP cosmos_validator_watcher_downtime_jail_duration Duration of the jail period for a validator in seconds
# TYPE cosmos_validator_watcher_downtime_jail_duration gauge
cosmos_validator_watcher_downtime_jail_duration{chain_id="cosmoshub-4"} 600
# TYPE cosmos_validator_watcher_min_signed_blocks_per_window gauge
cosmos_validator_watcher_min_signed_blocks_per_window{chain_id="cosmoshub-4"} 0.05
# HELP cosmos_validator_watcher_slash_fraction_double_sign Slash penaltiy for double-signing
# TYPE cosmos_validator_watcher_slash_fraction_double_sign gauge
cosmos_validator_watcher_slash_fraction_double_sign{chain_id="cosmoshub-4"} 0.05
# HELP cosmos_validator_watcher_slash_fraction_downtime Slash penaltiy for downtime
# TYPE cosmos_validator_watcher_slash_fraction_downtime gauge
cosmos_validator_watcher_slash_fraction_downtime{chain_id="cosmoshub-4"} 0.0001
.
.
.

```

Example Log for cosmoshub-4
```
12:30AM INF connected to https://cosmos-rpc.publicnode.com:443 chainID=cosmoshub-4 height=22945025
12:30AM INF connected to https://cosmos-rpc.polkachu.com:443 chainID=cosmoshub-4 height=22945026
12:30AM INF tracking validator D9F8A41B782AA6A66ADC81F953923C7DCE7B6001 alias=figment moniker=Figment
12:30AM INF starting HTTP server on :8080
12:30AM INF Updating slashing metrics for chain cosmoshub-4 Downtime jail duration:=10m0s Min signed per window:=0.050000000000000000 Signed blocks window:=10000 Slash fraction double sign:=0.050000000000000000 Slash fraction downtime:=0.000100000000000000 Slashing parameters for chain:=cosmoshub-4
12:30AM INF Tracked validator missed blocks: 20
12:30AM INF fetched staking validators and signing infos
#22945025 180/180 validators ✅ figment
#22945026 180/180 validators ✅ figment
#22945027 180/180 validators ✅ figment
#22945028 180/180 validators ✅ figment
#22945029 180/180 validators ✅ figment
#22945030 180/180 validators ✅ figment
```
---

Please let me know if I should add some additional code changes.

2024-11-08 19:02 UTC, MattKetmo commented
Hello @qwertzlbert thanks for your contribution. I will have a look next week :)

2024-11-12 19:08 UTC, MattKetmo requested changes

2024-11-12 19:58 UTC, qwertzlbert commented
@MattKetmo thanks for your quick and extensive review! I'll add the suggested changes as soon as possible.

2024-11-12 20:01 UTC, qwertzlbert commented on pkg/watcher/slashing.go
> +		return fmt.Errorf("failed to get signing infos: %w", err)
Makes sense 👍 I was using "signing infos" as the module to return missed blocks is called "SigningInfos" in the cosmos sdk

2024-11-12 20:25 UTC, qwertzlbert commented on pkg/crypto/utils.go
> +	panic("unknown pubkey type: " + consensusPubkey.TypeUrl)
Not without more changes unfortunately. `key.Address()` in `PubKeyBech32Address` requires the address represented in hex and not the string version.

2024-11-12 21:04 UTC, qwertzlbert commented on pkg/watcher/validators.go
> +func (w *ValidatorsWatcher) fetchSigningInfos(ctx context.Context, node *rpc.Node) error {
Added change to pass the option to the validator module and adhere to the `--no-slashing` flag

2024-11-12 21:05 UTC, qwertzlbert commented on pkg/watcher/validators.go
> +func (w *ValidatorsWatcher) fetchSigningInfos(ctx context.Context, node *rpc.Node) error {
Here: https://github.com/kilnfi/cosmos-validator-watcher/pull/85/files#diff-ae6edb7bc015f7259c9d543fbf4924e1846fdf3e4709d271c3824a0e0af2feafR149 
and here: 
https://github.com/kilnfi/cosmos-validator-watcher/pull/85/files#diff-a8dca88e6a20db698d1158e24fc8956626c9ec3e23f5da1871abae3e98ad6f9cR67

2024-11-12 21:07 UTC, qwertzlbert commented on pkg/crypto/utils.go
> +	panic("unknown pubkey type: " + consensusPubkey.TypeUrl)
I added an additional `PubKeyAddressHelper` function which returns the hexbyte value, but ensures the case switching is only done in one place

2024-11-12 21:09 UTC, qwertzlbert commented
@MattKetmo I addressed your comments and added your suggestions and required changes. Feel free to take another look whenever you have time

2024-11-15 09:00 UTC, MattKetmo approved these changes

2024-11-15 09:01 UTC, merged